# Generated by Django 5.2.5 on 2025-08-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateField(),
        ),
    ]
